export const TOGGLE_MOBILE = 'ERICK_SAURI/APP/TOGGLE_MOBILE';
export const UPDATE_LOCATION = 'ERICK_SAURI/APP/UPDATE_LOCATION'
export const TOGGLE_POPUP_MENU = 'ERICK_SAURI/APP/TOGGLE_POPUP_MENU';
export const TOGGLE_DROPDOWN_MENU = 'ERICK_SAURI/APP/TOGGLE_DROPDOWN_MENU';
export const ROUTING_TRANSITION_OUT = 'ERICK_SAURI/APP/ROUTING_TRANSITION_OUT';
export const ROUTING_TRANSITION_RESET = 'ERICK_SAURI/APP/ROUTING_TRANSITION_RESET';