export const TOGGLE_MOBILE = 'ERICK_SAURI/APP/TOGGLE_MOBILE';
export const TOGGLE_DARK_THEME = 'ERICK_SAURI/APP/TOGGLE_DARK_THEME';
export const TOGGLE_POPUP_MENU = 'ERICK_SAURI/APP/TOGGLE_POPUP_MENU';
export const TOGGLE_DROPDOWN_MENU = 'ERICK_SAURI/APP/TOGGLE_DROPDOWN_MENU';
export const TOGGLE_BACK_TO_TOP_BUTTON = 'ERICK_SAURI/APP/TOGGLE_BACK_TO_TOP_BUTTON';